### PR TITLE
CONTRIBUTING.md: try to codify merge policy

### PR DESCRIPTION
**Pull request by kevinburkesegment**
This reflects my understanding of the different stakeholders, and
tries to find a balance between that and ensuring forward progress is
possible. Please give me your thoughts.

### CODE REVIEW

**Review by thorfour — APPROVED** [review]
This LGTM though I would say maybe we wait for a consensus on this PR since it's codifying the rules.

**Review by achille-roussel — COMMENTED** [review]
Instead of "code review", what do you think about detailing when "approval" is necessary?

Generally I think we always need one maintainer to approve the PR, but it can be the submitter itself if they're a maintainer and the change falls in the first category. Then we would require least two maintainers to approve for the second category of use cases you've documented.

**Review by mdisibio — APPROVED** [review]
I think this is fair and strikes a good balance.  I'd still like to accept #39 and require approvals for PRs just to provide basic structure and diligence, but because each org has multiple maintainers (as in the case of Grafana Labs, Polar Signals), this still fits the spirit of these guidelines.  It can be assumed that it is easy to flag down another set of eyes within the same org.

**Review by joe-elliott — APPROVED** [review]
Given the number of people who are invested I this repo I think it shouldn't be too hard to get a code review when desired. I would like the submitter to make the effort to get a review even for the first set of changes.

**Review by metalmatze — APPROVED** [review]

**Pull request merged**
