### PR TITLE
compress/lz4: Use default Compressor for Fast LZ4 level

### PR DESCRIPTION
**Pull request by ngotchac**
I was wondering why the LZ4 compression was so much slower than Snappy, even in Fast mode (almost x5 slower). I found this issue: https://github.com/pierrec/lz4/issues/60 on LZ4's repo, which points out to the fact that using `lz4.CompressBlockHC` is slow and `lz4.CompressBlock` should be used.

So this PR does just that. It uses the default Compressor (`lz4.Compressor`) in Fast mode, and `lz4.CompressorHC` otherwise.

I'm not quite sure whether a compression level is actually necessary or wanted, I haven't found any reference of it in Parquet docs: https://github.com/apache/parquet-format/blob/master/Compression.md

Maybe there should rather be another Enum level for the Default Compressor?

### CODE REVIEW

**Comment by gernest** [comment]
`CompressorHC` gives  better compression ratio, switching to `Compressor` sacrifices this. We will need benchmarking numbers to justify this change.

Please share your user case and scenario where you think `Compressor` suits best. By default best compression ratios makes sense.

**Comment by ngotchac** [comment]
Agreed, `CompressorHC` is the best compression ratio, but it's far from the "best", as its compression speed can be very low compared to `Compressor`. I added a commit to my PR (which shouldn't get merged as is), which adds a couple of test data from https://github.com/klauspost/compress/tree/master/testdata for the compression tests and benchmarks. I added different levels of LZ4 HC compression, and added a new level called `Fastest` to use a `Compressor`.

Here are the results, from running
```bash
go test -benchmem -bench "BenchmarkEncode/(lz4|snappy)" ./compress/ -v
```

### Compression Ratio
  | e | gettysburg | html | Tom Sawyer | Pi | PNG
-- | -- | -- | -- | -- | -- | --
Snappy | 77.84% | 75.32% | 36.45% | 53.43% | 78.05% | 8.78%
LZ4 – Fastest | 100.39% | 85.47% | 41.04% | 58.46% | 98.14% | 5.34%
LZ4 – Fast | 69.52% | 76.23% | 35.11% | 48.69% | 69.58% | 4.64%
LZ4 – L1 | 69.52% | 76.23% | 35.13% | 48.69% | 69.58% | 4.88%
LZ4 – L5 | 69.52% | 76.23% | 35.11% | 48.69% | 69.58% | 4.70%
LZ4 – L9 | 69.52% | 76.23% | 35.11% | 48.69% | 69.58% | 4.64%

### Compression Speed 
  | e | gettysburg | html | Tom Sawyer | Pi | PNG
-- | -- | -- | -- | -- | -- | --
Snappy | 248.71 MB/s | 612.96 MB/s | 730.10 MB/s | 255.77 MB/s | 240.25 MB/s | 1976.59 MB/s
LZ4 – Fastest | 12243.05 MB/s | 379.48 MB/s | 677.99 MB/s | 249.67 MB/s | 395.64 MB/s | 3147.58 MB/s
LZ4 – Fast | 59.75 MB/s | 15.67 MB/s | 52.50 MB/s | 27.20 MB/s | 58.64 MB/s | 6.11 MB/s
LZ4 – L1 | 58.54 MB/s | 15.74 MB/s | 57.35 MB/s | 27.10 MB/s | 58.96 MB/s | 155.30 MB/s
LZ4 – L5 | 58.59 MB/s | 15.58 MB/s | 52.76 MB/s | 26.48 MB/s | 59.23 MB/s | 14.41 MB/s
LZ4 – L9 | 60.27 MB/s | 15.65 MB/s | 53.74 MB/s | 26.26 MB/s | 58.16 MB/s | 6.17 MB/s
  |   |   |   |   |   |  
Speed up (Fastest vs. Fast) | 204.90 | 24.22 | 12.91 | 9.18 | 6.75 | 515.15

We can see that the compression ratio is only worse in **very** random data (Pi and e), but the compression speed as at least 10x faster, up to 500x

If these results are appealing, let me know what would be the best way to integrate this new "compression level". A new `Fastest` level might be the best solution, as it doesn't change the default; although it could be argued that the default should actually be this level.

**Comment by fpetkovski** [comment]
Changing the default could be considered a breaking change, so adding a new level might be a better option.

**Comment by ngotchac** [comment]
Any update on this feature ? :slightly_smiling_face:

**Review by achille-roussel — APPROVED** [review]
Hello @ngotchac, thanks for bringing this back up to the forefront!

The change looks good to me, we're adding a way to configure the compression level which doesn't impact existing programs that may depend on the historical behavior, plus it is well tested 👍 

I'll mark this as approved but wait before merging in case another contributor wants to chime in and share another opinion.

**Comment by joe-elliott** [comment]
I believe this is backwards compatible and will continue to read old files correctly. So we're good. Seems like a solid perf improvement.

**Pull request merged**
