### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by joe-elliott**
Proposing using a CODEOWNERS file to help with maintaining the project. I will add whatever github handles make sense and alphabetize them before merging.

CODEOWNERS can make it easy to request reviews. We can also require a review from a code owner before merging.

There are likely other ways to accomplish this and I don't care if we choose a different path, but I'd like to add some structure/policy to this repo.

Per conversation in https://github.com/parquet-go/parquet-go/issues/36

### CODE REVIEW

**Comment by brancz** [comment]
Please add myself, @thorfour, @asubiotto and @metalmatze from Polar Signals side.

**Comment by fpetkovski** [comment]
For transparency, I reached out to @kevinburke when I saw the initial issue since I didn't want the repo to be abandoned. I've been granted maintainer permissions as well, but we only use the library internally and have no commercial offering based on it. I would not mind if my permissions are taken away as long as there are enough people to review PRs against the repository.

**Comment by gernest** [comment]
From this comment https://github.com/parquet-go/parquet-go/issues/36#issuecomment-1648063492 I don't think its appropriate to include me in this file.

**Comment by Pryz** [comment]
Please add myself as well. I will help to maintain the repo and triage issues.

**Comment by joe-elliott** [comment]
@gernest 

I will gladly remove you from this PR as desired, but please know that your contributions were welcome. If you have interest in the future on collaborating in this repo the door is always open.

**Comment by joe-elliott** [comment]
@fpetkovski Added your handle. I think at this point anyone willing to put time into the repo should be included. In 6 or 12 months we will likely get a better feel for who really has the time to invest and can whittle things down appropriately.

**Comment by kevinburkesegment** [comment]
"Unknown owner on line 1: make sure @metalmatze exists and has write access to the repository"

**Comment by achille-roussel** [comment]
I went ahead and merged this, it will be helpful to scale the maintenance of this repository, we can figure out the permission issues independently.

**Pull request merged**
