### PR TITLE
fix:  wrong file in testdata

### LINKED ISSUE #4: Test failure
Attempting to get the tests passing to merge a rewrite references change, I get the following error:

```
FAIL: TestOpenFile (2.01s)
    --- FAIL: TestOpenFile/testdata/issue368.parquet (0.00s)
        file_test.go:38: reading parquet file metadata: decoding thrift payload: -10:FIELD<?>: skipping unsupported thrift type 15
FAIL
FAIL	github.com/parquet-go/parquet-go	39.395s
ok  	github.com/parquet-go/parquet-go/bloom	0.02[7](https://github.com/parquet-go/parquet-go/actions/runs/5534777733/jobs/10100177839#step:5:8)s
ok  	github.com/par
```

### PR DESCRIPTION
**Pull request by gernest**
fixes #4 

I noticed that checksum of `testdata/issue368.parquet` was different meaning
we were working with the wrong file.

There is no need for further investigation on why we end up with a different
file.

While on this I discovered another issue that has been around for a while which was affecting the same test, so it is fair to include that fix in this PR ( details on the commits)

### CODE REVIEW

**Comment by kevinburkesegment** [comment]
So FWIW I think I modified this yesterday by opening the file in vim which would have appended a newline to the file. You might want to check and see if reverting the change I made yesterday fixes the checksum.

**Comment by gernest** [comment]
> So FWIW I think I modified this yesterday by opening the file in vim which would have appended a newline to the file. You might want to check and see if reverting the change I made yesterday fixes the checksum.

Indeed, but this `TestOpenFile` is flakey, the commit that properly resets the  reused `format.PageHeader` stabilise it.

What do you think if we just leave the checksum fix and the  reset of `format.PageHeader` as is  and chalk it up as fixing/stabilising  `TestOpenFile`  I can update the title to something like stabilise ``TestOpenFile``

I was hard to bisect  when `TestOpenFile` was this volatile.   

I'm happy to hunt down and revert change you think might be the culprit,  what do you think?

**Comment by kevinburkesegment** [comment]
Whatever you think is best is fine with me, don't do extra work on my behalf, let's just get this fixed

**Comment by gernest** [comment]
Cool, I'm merging this for now. I really need to check on our workflow file. It makes me unease to tiptoe around new go features with the fear of breaking old go versions support in our runner matrix

**Comment by kevinburkesegment** [comment]
@gernest Whoops - there's one more change. TestIssue368 should also be marked unskipped.

**Comment by gernest** [comment]
nice catch! I'm on it.

**Pull request merged**
